public class Catch
{
    public static void main(String [] args)
    {
        try{
            Broken broke = new Broken();
            System.out.println(" Testing");
            // Modify the code to catch the exceptions generated by Broken.cracked().
            broke.cracked();
        }
        catch(Exception e){
            if(e instanceof NullPointerException){
                System.out.println("NullPointerException");
            }
            if(e instanceof ArrayIndexOutOfBoundsException){
                System.out.println("ArrayIndexOutOfBoundsException");
            }
            if(e instanceof ArithmeticException){
                System.out.println("ArithmeticException");
            }
        }
        finally{
            System.out.println("Finally!");
        }
    }
}